### ISSUE TITLE
doesn't work since 1.1.2

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub-contrib/popover-vcard#16]
**v1.1.1** - It works!
![image](https://github.com/humhub-contrib/popover-vcard/assets/91057837/395dd4dc-36ea-4bfc-b4b3-419f04c10e50)

**v1.1.2** - Error log
```
#8 [internal function]: humhub\modules\popovervcard\controllers\IndexController->actionLoad()
#9 /home/ntwr3147/SITES/subdomain.domain.org/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#10 /home/ntwr3147/SITES/subdomain.domain.org/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#11 /home/ntwr3147/SITES/subdomain.domain.org/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#12 /home/ntwr3147/SITES/subdomain.domain.org/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#13 /home/ntwr3147/SITES/subdomain.domain.org/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#14 /home/ntwr3147/SITES/subdomain.domain.org/index.php(25): yii\base\Application->run()
#15 {main}
```
v1.1.2 - Info log
```
$_GET = [
'r' => 'popover-vcard/index/load'
]

$_SERVER = [
'PATH' => '/usr/local/bin:/usr/bin:/bin'
'TEMP' => '/tmp'
'TMP' => '/tmp'
'TMPDIR' => '/tmp'
'PWD' => '/'
'LSCAPI_CRIU_SYNC_FD' => '7'
'HTTP_ACCEPT' => '*/*'
'HTTP_ACCEPT_LANGUAGE' => 'fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7'
'CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8'
'CONTENT_LENGTH' => '5'
'HTTP_COOKIE' => '_identity=a3228b8f4764bea7686ceeda01d3ba5525bcb8822940906fdc69a0c04153e2f7a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A46%3A%22%5B1%2C%22SIPNVj55Rfic3sD0WuFOp4bFuRSiG6ON%22%2C2592000%5D%22%3B%7D; _csrf=66cae8e7981467034c200e96ff0e1054b13b0fa5a3aa22b60429bbe33a5e42eca%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22qui_ydr-3BYZD7BEsjOoSC2BZnC0evRo%22%3B%7D; PHPSESSID=r70256rnknpp8t93bai7v9qjn7'
'HTTP_HOST' => 'subdomain.domain.org'
'HTTP_REFERER' => 'https://subdomain.domain.org/index.php?r=dashboard%2Fdashboard'
'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
'HTTP_X_COUNTRY_CODE' => 'FR'
'HTTP_X_AUTONOMOUS_SYSTEM' => '12322'
'HTTP_X_FORWARDED_PROTO' => 'https'
'HTTP_X_FORWARDED_PORT' => '443'
'HTTP_X_SSL' => 'yes'
'HTTP_SEC_CH_UA' => '\"Not_A Brand\";v=\"8\", \"Chromium\";v=\"120\", \"Google Chrome\";v=\"120\"'
'HTTP_X_CSRF_TOKEN' => '5x5Q2cPKevyRNE33GLVcadUxv4r7JuxzJb8EVpREi6-WazmGuq4I0aJ2FK1cgh4splvw5ahl3jF_0Udm8TLZwA=='
'HTTP_SEC_CH_UA_MOBILE' => '?0'
'HTTP_HUMHUB_VIEW_CONTEXT' => 'dashboard'
'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest'
'HTTP_SEC_CH_UA_PLATFORM' => '\"Windows\"'
'HTTP_ORIGIN' => 'https://subdomain.domain.org'
'HTTP_SEC_FETCH_SITE' => 'same-origin'
'HTTP_SEC_FETCH_MODE' => 'cors'
'HTTP_SEC_FETCH_DEST' => 'empty'
'UNIQUE_ID' => 'ZZsBAnpmvNialHJP5G7hJAAAAko'
'HTTPS' => 'on'
'SERVER_SIGNATURE' => ''
'SERVER_SOFTWARE' => 'Apache'
'SERVER_NAME' => 'subdomain.domain.org'
'SERVER_ADDR' => '109.234.161.56'
'SERVER_PORT' => '443'
'REMOTE_ADDR' => '82.65.224.172'
'DOCUMENT_ROOT' => '/home/ntwr3147/SITES/subdomain.domain.org'
'REQUEST_SCHEME' => 'https'
'CONTEXT_PREFIX' => ''
'CONTEXT_DOCUMENT_ROOT' => '/home/ntwr3147/SITES/subdomain.domain.org'
'SERVER_ADMIN' => 'webmaster@subdomain.domain.org'
'SCRIPT_FILENAME' => '/home/ntwr3147/SITES/subdomain.domain.org/index.php'
'REMOTE_PORT' => '33314'
'SERVER_PROTOCOL' => 'HTTP/1.1'
'REQUEST_METHOD' => 'POST'
'QUERY_STRING' => 'r=popover-vcard%2Findex%2Fload'
'REQUEST_URI' => '/index.php?r=popover-vcard%2Findex%2Fload'
'SCRIPT_NAME' => '/index.php'
'PHP_SELF' => '/index.php'
'REQUEST_TIME_FLOAT' => 1704657154.6541
'REQUEST_TIME' => 1704657154
]
```

**Comment by luke-** [comment]
@Gilbertdelyon Version 1.1.3 should solves this issue.

**Comment by Gilbertdelyon** [comment]
It works! Thank you.
